### PR TITLE
chore: update naj

### PR DESCRIPTION
**Pull request by willemneal**

### CODE REVIEW

**Comment by willemneal** [comment]
@volovyk-s @austinabell @ChaoticTempest

Is there any way to allow my account to trigger CI?

**Review by volovyk-s — APPROVED** [review]

**Comment by volovyk-s** [comment]
@willemneal I guess the only way to do that is to turn it on for all developers. I don't have access to the settings in this repo.
Sometimes I want to see CI status for external contributions too (in all repos) so I'm not against that. @MaximusHaximus do you have access? Are there any security concerns? I think that if the project is using GitHub actions, it should be fine, since it's free and runs on GitHub infrastracture.

**Comment by willemneal** [comment]
@volovyk-s Did it pass CI?

**Comment by volovyk-s** [comment]
I was not able to start the CI in this PR. So I tested it locally.
Also, now you can see the status in the main branch. All good.

**Comment by ChaoticTempest** [comment]
I think it's just that github-actions is only listening on a push. Think we can change it to PRs as well and that will allow us to trigger CI for external people

**Pull request merged**
