### PR TITLE
feat-issue-215: increase randoness to decrease the rate of port colli…

### PR DESCRIPTION
**Pull request by fospring**
https://github.com/near/workspaces-js/issues/215

### CODE REVIEW

**Comment by fospring** [comment]
when I debug, I found error log:
```
  Error (TypedError) {
    context: undefined,
    type: 'KeyNotFound',
    message: 'Can not sign transactions for account test.near on network sandbox, no matching key pair found in InMemorySigner(UnencryptedFileSystemKeyStore(/private/var/folders/gq/vqxz79yn511772w0bmy58ylc0000gn/T/sandbox/fe2348f4-406d-4ebd-a94a-e50030da3931)).',
  }
```
so I check this log:
```
cd /private/var/folders/gq/vqxz79yn511772w0bmy58ylc0000gn/T/sandbox/fe2348f4-406d-4ebd-a94a-e50030da3931
cat sandboxServer.log
```
image
there was a panic info with `Address already in use`
when I run single testfile it won't occur this error, only when we run many testfiles concurrently it many occur sometimes, so the initRpcPort may conflict between those testcase or already use by other program

**Comment by fospring** [comment]
every `Worker.init()` test run near rpc node by `SandboxServer.start()`, if the port is already in used it will fail to run rpc node: https://github.com/near/workspaces-js/blob/main/packages/js/src/server/server.ts#L139C18-L139C18
```ts
  async start(): Promise<SandboxServer> {
    debug('Lifecycle.SandboxServer.start()');
    const args = [
      '--home',
      this.homeDir,
      'run',
      '--rpc-addr',
      `0.0.0.0:${this.port}`,
      '--network-addr',
      `0.0.0.0:${await SandboxServer.nextPort()}`,
    ];
    if (process.env.NEAR_WORKSPACES_DEBUG) {
      const filePath = join(this.homeDir, 'sandboxServer.log');
      debug(`near-sandbox logs writing to file: ${filePath}`);
      const fd = await open(filePath, 'a');
      this.subprocess = spawn(SandboxServer.binPath, args, {
        env: {RUST_BACKTRACE: 'full'},
        // @ts-expect-error FileHandle not assignable to Stream | IOType
        stdio: ['ignore', 'ignore', fd],
      });
      this.subprocess.on('exit', async () => {
        await fd.close();
      });
    } else {
      this.subprocess = spawn(SandboxServer.binPath, args, {
        stdio: ['ignore', 'ignore', 'ignore'],
      });
    }
```

**Comment by ailisp** [comment]
Excellent analysis and fix! Thank you!

**Comment by fospring** [comment]
> Excellent analysis and fix! Thank you! Is it possible to completely prevent this error? By making a more robust version `nextAvailable`, or pre-calculate all ports before tests, or whatever simpler fix.

yep, we need to check whther this port is in used by other programs or other parallel testcases use `Worker.int()`

**Pull request merged**
